version: '3.8'

services:
  fedora-ssh:
    build: .
    container_name: agendise
    hostname: fedora-dev
    environment:
      - USER_PASSWORD=evolve@NAS!
      - TZ=Asia/Singapore
    volumes:
      # Bind mount to sparse image (mounted at /mnt/agent_storage on host)
      - /mnt/agent_storage:/home/evolve
    network_mode: "host"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 8G
