version: '3.8'

services:
  fedora-ssh:
    build: .
    container_name: agendise2
    hostname: fedora-dev2
    environment:
      - USER_PASSWORD=evolve@NAS!
      - TZ=Asia/Singapore
      # - WGPU_BACKEND=vulkan # force vulkan
    volumes:
      # Bind mount to sparse image (mounted at /mnt/agent_storage on host)
      - /mnt/agent_storage2:/home/evolve
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    ports:
      - "18889:22"
      - "18790:18789"
      - "23000:3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 8G
